# Generated by Django 3.2.2 on 2021-05-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0003_payement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payement',
            new_name='Payment',
        ),
    ]
