# Generated by Django 3.2.2 on 2021-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0005_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
