# Generated by Django 3.2.2 on 2021-05-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0006_car_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='status',
            new_name='status1',
        ),
    ]
